### ISSUE TITLE
Cross platform?

### ISSUE THREAD

**Issue by OutshineIssue** [Firefox0/Youtube-Lyrics#1]
I tried changing the API namespaces from browser.* to chrome.* but I'm still getting lots of errors.

**Comment by Firefox0** [comment]
Hello.

Sorry for the late response. I have rewritten most of the addon and added and improved many things. Chrome/Manifest V3 is now supported too.

You are right. Changing the namespaces is not enough to fix the issue because there was also a CORS problem since the content script tried to fetch data which is not allowed anymore if you use manifest v3 which is now the standard for all Chrome addons.

The release should be this week.
